### ISSUE TITLE
Add Basic (CRUD) Functionalities in the Project's Mockup on Figma

### ISSUE THREAD

**Issue by SauveJeanLuc** [SauveJeanLuc/coffee-tasks#19]
Currently, on the Project Mockup, only a Pop-Up to add a new task is designed.
The rest of the basic functionalities awaits your help, and it's on the UI/UX you'll provide that the whole project implementation will base.
 
 To get started, make a request for Edit Privileges on the
 [Figma Design](https://www.figma.com/file/2DdRHkoszU7lxTvcyBchJ8/React-TODO?node-id=0%3A1) And Thereafter, CREATE A PR/MR TO TRACK IT

**Comment by Rick-mad-lab** [comment]
ok 
I will work on this part too @SauveJeanLuc assign me.

**Comment by Rick-mad-lab** [comment]
app is looking modern but too simple can I add more functionality?

**Comment by SauveJeanLuc** [comment]
Yh yh, It's yours again @Rick-mad-lab.
Go for it.

**Comment by SauveJeanLuc** [comment]
> app is looking modern but too simple can I add more functionality?

But with any functionality other than basic CRUD, you can open an issue for it, and if accepted, then a PR to track Figma changes, and if all is accepted we merge everything by October 1st.

**Comment by Rick-mad-lab** [comment]
Okie

**Comment by pobrebobby** [comment]
If you need any help let me know.

**Comment by SauveJeanLuc** [comment]
@pobrebobby, glad you've joined 🥂.

**Comment by pobrebobby** [comment]
<img width="6010" alt="Coffee Tasks v2" src="https://user-images.githubusercontent.com/115002742/194346947-4bef97c7-b238-4b59-b803-358d95b3d104.png">

**Comment by SandeshGC** [comment]
@SauveJeanLuc @Rick-mad-lab @pobrebobby  I have a suggestion. 
Instead of clicking on the "options" icon to edit/delete a task, you could add icons like 
![image](https://user-images.githubusercontent.com/59115123/194739952-41b6edaa-f67e-4d0e-a58b-bd65cae55746.png) for deleting task
and ![image](https://user-images.githubusercontent.com/59115123/194740008-a74612d1-cb3e-47dc-9ebf-aca03646692b.png) for editing the task.

I think this would be easy for the user. What do you think?

**Comment by pobrebobby** [comment]
@SandeshGC @Rinshin-Jalal Please take a look at Pull Request #82 Updated Figma file if you have any suggestions. Thanks.
