### ISSUE TITLE
Add Delete Existing Task Functionality

### ISSUE THREAD

**Issue by SauveJeanLuc** [SauveJeanLuc/coffee-tasks#5]
There's currently no way to delete an existing Task.
**NB:** 
* This should be done by using Local Storage.
* This waits for issue #2

**Comment by SauveJeanLuc** [comment]
Yup, It's yours @ItzNesbroDev

**Comment by aritroCoder** [comment]
Can I work on this?

**Comment by SauveJeanLuc** [comment]
Yup, no prob @aritroCoder.

**Comment by aritroCoder** [comment]
![image](https://user-images.githubusercontent.com/92646038/193444496-2ac1889d-af81-463f-b49d-d009d9acf1f6.png)
I want to point out some things we need to implement before doing this task. 
1. To make the delete task button accessible, we need to fix another issue (issue 1, closing of the pop up)
2. To make delete task button work, we need to give a unique id to each task (again this is a part of the create task functionality issue), so that we can reference a task by its unique id to delete it.

As both of these are part of their own seperate issues, how should I proceed with implementing this feature?
my suggesstion is you can reopen issue 2 and assign it to me, then I will make the localstorage store a unique id for each task, which can be used to implement the delete functionality here

**Comment by SauveJeanLuc** [comment]
@aritroCoder , by now I think the 2 are compete.
And we'll maybe have to wait for the design a little so as to know what to do next.
